Add CLI commands for setting and getting plugin configs
brickadia-community/omegga pull request #39
Opened 2022-07-20 15:52 UTC by foxydevloper

This PR adds the following commands:
`omegga list-config <pluginName>`
`omegga get-config <pluginName> <configName>`
`omegga set-config <pluginName> <configName> <configValue>`

These commands allow you to alter plugin configuration using Omegga through command line.
This currently supports the config types boolean, number, string, and enum.

2022-07-20 16:58 UTC, Meshiest requested changes

2022-07-20 16:58 UTC, Meshiest commented on src/cli/plugin.ts
> +function pluginLoaderFactory() {
You should be able to make the `omegga` in the PluginLoader constructor optional:

```ts
  constructor(pluginsPath: string, omegga?: Omegga) {
    this.path = pluginsPath;
    this.omegga = omegga;
    this.store = Datastore.create({
      filename: path.join(omegga.dataPath, soft.PLUGIN_STORE),
      autoload: true,
    });
    this.store.persistence.setAutocompactionInterval(1000 * 60 * 5);
    this.formats = [];
    this.plugins = [];

    // soon to be deprecated !help
    omegga?.on('chatcmd:help', this.showHelp.bind(this));

    // use /plugins to get help
    omegga?.on('cmd:plugins', this.showHelp.bind(this));
  }
```

also you should be able to move the body of the .map.filter.map in PluginLoader.scan to a separate method called `scanPlugin(path: string)`

this line can be moved from `src/omegga/server.ts` to the PluginLoader's constructor:
    `this.pluginLoader.loadFormats(join(__dirname, 'plugin'));`

2022-07-20 16:58 UTC, Meshiest commented on src/main.ts
> +program
please also add a `reset-config [name]` to reset all or one of the config fields

2022-07-20 17:21 UTC, Meshiest commented on src/cli/plugin.ts
> +function pluginLoaderFactory() {
may need to replace `pluginsPath` with just `workDir` and make these changes:

`this.path = path.join(workDir, soft.PLUGIN_PATH)`

`filename: path.join(workDir, soft.DATA_PATH, soft.PLUGIN_STORE)`

2022-07-20 18:15 UTC, Meshiest requested changes

2022-07-20 18:15 UTC, Meshiest commented on src/main.ts
> +  .command('reset-config <pluginName> <configName>')
should be `[configName]`

<required>

[optional]

2022-07-20 18:15 UTC, Meshiest commented on src/omegga/plugin.ts
> +    Logger.verbose('Creating loading plugins');
this was a typo in the original command - should just be `Loading plugin formats`

2022-07-26 20:01 UTC, Meshiest commented
still waiting on the other changes

2022-07-26 20:17 UTC, Meshiest requested changes

2022-07-26 21:27 UTC, Meshiest commented on src/cli/plugin.ts
> +  const omegga = new Omegga(workDir, config, options);
we shouldn't need omegga anymore for plugin loaders

2022-07-26 21:39 UTC, Meshiest approved these changes

2022-07-26 22:24 UTC, foxydevloper commented
done

2022-07-27 00:26 UTC, merged